# Generated by Django 5.1.4 on 2025-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test__', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('customer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_type_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['customer_type_id'],
            },
        ),
    ]
