# Generated by Django 5.1.4 on 2025-01-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test__', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_fathers_name_hindi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_name_hindi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
